[all]
[localhost]
local ansible_connection=local ansible_shell_type=sh ansible_remote_tmp=./temp/

[controller_win]
winhost201 ansible_host=192.168.0.139

[laboratorio9003]
winhost202 ansible_host=192.168.0.11 posicao=2
; winhost203 ansible_host=192.168.1.203 posicao=3
; winhost204 ansible_host=192.168.1.204 posicao=4
; winhost205 ansible_host=192.168.1.205 posicao=5
; winhost206 ansible_host=192.168.1.206 posicao=6
; winhost207 ansible_host=192.168.1.207 posicao=7
; winhost208 ansible_host=192.168.1.208 posicao=8
; winhost209 ansible_host=192.168.1.209 posicao=9
; winhost210 ansible_host=192.168.1.210 posicao=10
; ;winhost211 ansible_host=192.168.1.211 posicao=11
; winhost212 ansible_host=192.168.1.212 posicao=12
; winhost213 ansible_host=192.168.1.213 posicao=13
; winhost214 ansible_host=192.168.1.214 posicao=14
; winhost215 ansible_host=192.168.1.215 posicao=15
; winhost216 ansible_host=192.168.1.216 posicao=16
; winhost217 ansible_host=192.168.1.217 posicao=17
; winhost218 ansible_host=192.168.1.218 posicao=18
; winhost219 ansible_host=192.168.1.219 posicao=19
; winhost220 ansible_host=192.168.1.220 posicao=20
; winhost221 ansible_host=192.168.1.221 posicao=21
; winhost222 ansible_host=192.168.1.222 posicao=22
; winhost223 ansible_host=192.168.1.223 posicao=23
; winhost224 ansible_host=192.168.1.224 posicao=24
; winhost225 ansible_host=192.168.1.225 posicao=25
; winhost226 ansible_host=192.168.1.226 posicao=26

[all:vars]
ansible_port=2313
ansible_ssh_common_args="-o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=~/.ssh/cm-%r@%h:%p"
ansible_remote_tmp=C:\Temp\ansible
ansible_user="imale"
; ansible_user="Laboratório"
ansible_connection=ssh
ansible_shell_type=powershell
ansible_ssh_retries=3
ansible_port=2313
packages_list=packages.txt
; ansible_ssh_private_key_file=~/.ssh/id_laboratorio
ansible_ssh_timeout=30
; # Sub-rede das 3 SSIDs (é 1 IP fixo no adaptador Wi-Fi; ele vale para todas as redes)
; wifi_prefix=192.168.1
; wifi_gateway=192.168.1.1
; wifi_dns=['8.8.8.8',]   ; pode ser 1 ou N DNS
; wifi_prefix_len=24
; # Nome do adaptador Wi-Fi (ajuste se for “Wi-Fi 2”, etc.)
; wifi_adapter_guess=Wi-Fi
; # Segredos (coloque no Ansible Vault em produção!)
; wifi_key_mcc_uerj="mccuerj3247"
; wifi_key_mestrado="mccuerj3247"
