[all]
[localhost]
local ansible_connection=local ansible_shell_type=sh ansible_remote_tmp=./temp/

[controller_win]
controller ansible_host=192.168.0.139

[nodes]
node1 ansible_host=192.168.0.11

[all:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=~/.ssh/cm-%r@%h:%p"
ansible_remote_tmp=C:\Temp\ansible
ansible_user={{ lookup('env', 'USER') }}
ansible_connection=ssh
ansible_shell_type=powershell
ansible_ssh_retries=3
ansible_port={{ lookup('env', 'PORT') }}
ansible_ssh_timeout=30
