[all]
[localhost]
local ansible_connection=local ansible_shell_type=sh

[controller_win]
winhost201 ansible_host=192.168.0.139 posicao=1

[laboratorio9003]
winhost202 ansible_host=192.168.0.11 posicao=2

[all:vars]
ansible_port=2313
ansible_ssh_common_args="-o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=~/.ssh/cm-%r@%h:%p"
ansible_remote_tmp=C:\Temp\ansible
ansible_user="imale"
ansible_connection=ssh
ansible_shell_type=powershell
ansible_ssh_retries=3
ansible_port=2313
ansible_ssh_timeout=30
