---
- name: Instalar pacotes nos nodes a partir do share do controller (com usuário/senha)
  hosts: nodes
  serial: 10
  gather_facts: no
  collections:
    - ansible.windows

  tasks:
    - import_tasks: "tasks/choco_bootstrap.yml"
    - import_tasks: "tasks/choco_packages.yml"
  ignore_errors: true
  tags: [choco, packages, bootstrap]

  # =========================================================
  # PLAY 4: Configurar o conda
  # =========================================================
- name: Configurar Miniconda com .condarc personalizado
  hosts: nodes
  gather_facts: false
  vars:
    # vars úteis (coloque onde preferir: group_vars/host_vars/vars:)
    # -----------------------------------------------------------------------------
    # Caminho do conda.exe do Miniconda “base”
    # Diretórios otimizados (cache/envs)
    conda_root: "D:\\tools\\mambaforge"
    conda_envs: "D:\\tools\\mambaforge\\envs"
    remove_meta_timeout_sec: 30
    conda_pkgs: "D:\\tools\\mambaforge\\pkgs"

  tasks:
    - import_tasks: "tasks/conda_configure.yml"
  tags: [conda]

- name: Configurar o neovim
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Clonar configurações do Neovim no Windows
      win_shell: |
        $configDir = "$env:LOCALAPPDATA\nvim"
        if (!(Test-Path $configDir)) {
          git clone https://github.com/alexandre07/nvim $configDir
        } else {
          Set-Location $configDir
          git pull
        }
      args:
        executable: pwsh
      register: resultado

    - name: Exibir saída do clone/pull
      debug:
        var: resultado.stdout
  tags: [neovim]
