---
# =========================================================
# PLAY 1: Instalar wsl
# =========================================================
- name: Instalar WSL e configurar o Ubuntu para Docker Desktop no Windows
  gather_facts: yes
  hosts: laboratorio9003
  tasks:
    - import_tasks: "tasks/wsl_install.yml"

    - name: Reiniciar o host
      win_reboot:
        reboot_timeout: 600  # Tempo máximo de espera (em segundos) para o reinício
        pre_reboot_delay: 60
        test_command: whoami  # Comando para testar se a máquina está online após o reinício      win_reboot:
  tags: wsl

# =========================================================
# PLAY 2: Instalar pacotes via choco
# =========================================================
- name: Instalar pacotes via choco
  hosts: controller_win
  gather_facts: no
  vars:
    choco_lib:      'C:\ProgramData\chocolatey\lib'
    repo_root:      'C:\choco_repo'
    repo_nupkg:     'C:\choco_repo\nupkg'
    share_name:     'ChocoRepo'
    choco_source_name: "choco_repo"
    controller_smb_host: '192.168.0.139'   # opcional, só pra mensagem final
    choco_unc:  '\\{{ controller_smb_host }}\{{ share_name }}'
    unc_export: '{{ choco_unc }}\export'
    unc_nupkg:  '{{ choco_unc }}\nupkg'
    # se precisar aplicar um source extra durante a instalação do controller, adicione aqui
    extra_source: ""   # ex: " -s https://community.chocolatey.org/api/v2/"

  tasks:
    - import_tasks: "tasks/choco_prep_packages.yml"
    - import_tasks: "tasks/choco_share_packages.yml"
    
      ignore_errors: true
  tags: [choco, packages, bootstrap]

- name: Instalar nos nodes
  hosts: laboratorio9003
  gather_facts: no
  vars:
    share_name:     'ChocoRepo'
    local_export:        'C:\Windows\Temp\choco_export'
    choco_source_name: "choco_repo"
    controller_smb_host: '192.168.0.139'   # opcional, só pra mensagem final
    choco_unc: '\\{{ controller_smb_host }}\{{ share_name }}'
    unc_export: '{{ choco_unc }}\export'
    unc_nupkg:  '{{ choco_unc }}\nupkg'
    # se precisar aplicar um source extra durante a instalação do controller, adicione aqui
    extra_source: ""   # ex: " -s https://community.chocolatey.org/api/v2/"

  tasks:
    - import_tasks: "tasks/choco_install_nodes.yml"
  ignore_errors: true
  tags: [choco, packages, bootstrap]

# =========================================================
# PLAY 3: Configurar MySQL e DBeaver nos hosts
# =========================================================
- name: Instalar e configurar MySQL + DBeaver nos HOSTS
  hosts: all
  gather_facts: no
  vars:
    mysql_root_password: "laboratorio"
    dbeaver_src: "data-sources.json"
    dbeaver_dst_dir: "C:\\Users\\Laboratório\\AppData\\Roaming\\DBeaverData\\workspace6\\General\\.dbeaver"
    dbeaver_dst_file: "{{ dbeaver_dst_dir }}\\data-sources.json"
    dbeaver_credential: "credentials-config.json"
    dbeaver_dst_credential: "{{ dbeaver_dst_dir }}\\credentials-config.json"
  tasks:
    - import_tasks: "tasks/mysql_install.yml"
      ignore_errors: true


# =========================================================
# PLAY 4: Criar um container postgresql
# =========================================================
- name: Habilitar docker e iniciar postgresql
  hosts: all
  tasks:
    - import_tasks: "tasks/docker_start.yml"
  tags: docker
  ignore_errors: true


# =========================================================
# PLAY 5: Desligar tudo
# =========================================================
- name: Desligar os hosts após a execução
  hosts: all
  tasks:
    - name: Criar um container POSTGRESQL
      win_command: shutdown /s /f /t 0
      ignore_errors: yes  # Ignorar erros caso o comando não funcione
  tags: mysql


