- name: Habilitar e iniciar o serviço Docker no Windows
  win_service:
    name: com.docker.service  # Nome do serviço do Docker
    start_mode: auto          # Garantir que o serviço inicie automaticamente com o Windows
    state: started            # Iniciar o serviço, caso ainda não esteja em execução

- name: Pausa de 20 segundos para iniciar o container
  pause:
    seconds: 20

#=============================================================
# Criação de volumes
#=============================================================

- name: Criar volume Docker para MySQL
  community.docker.docker_volume:
    name: mysql_data
    state: present

- name: Criar volume Docker para POSTGRESQL
  community.docker.docker_volume:
    name: postgres_data
    state: present

#=============================================================
# Criação do container postgresql
#=============================================================
- name: Criar um container POSTGRESQL
  community.docker.docker_container:
    name: postgres_container
    image: postgres:latest
    state: started
    restart_policy: always
    published_ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "laboratorio"
      POSTGRES_USER: "laboratorio"
      POSTGRES_DB: "laboratorio"
    volumes: ["postgres_data:/var/lib/postgresql/data"]


#=============================================================
# Criação do container MySQL
#=============================================================
- name: Criar um container MYSQL
  community.docker.docker_container:
    name: mysql_container
    image: mysql:latest
    state: started
    restart_policy: always
    published_ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "laboratorio"
      MYSQL_USER: "laboratorio"
      MYSQL_PASSWORD: "laboratorio"
      MYSQL_DATABASE: "laboratorio"
    volumes: ["mysql_data/var/lib/mysql"]
