---
- name: Ativar recurso WSL (cliente Windows)
  ansible.windows.win_optional_feature:
    name: Microsoft-Windows-Subsystem-Linux
    state: present
    include_parent: yes
  register: feat_wsl
  tags: wsl

- name: Ativar recurso VirtualMachinePlatform (cliente Windows)
  ansible.windows.win_optional_feature:
    name: VirtualMachinePlatform
    state: present
    include_parent: yes
  register: feat_vmp
  tags: wsl

- name: Reboot se algum recurso foi alterado
  ansible.windows.win_reboot:
  when: (feat_wsl.changed | default(false)) or (feat_vmp.changed | default(false))
  tags: wsl
  
- name: Instalar o WSL
  win_shell: |
        Start-Process -FilePath "wsl.exe" -ArgumentList "--install" -Wait -Verb RunAs
  tags: wsl
  
- name: Definir WSL2 como padrão
  win_shell: |
        Start-Process -FilePath "wsl.exe" -ArgumentList "-set-default-version 2" -Wait -Verb RunAs
 tags: wsl

- name: Instalar a distribuição Ubuntu
  win_shell: |
        Start-Process -FilePath "wsl.exe" -ArgumentList "--install -d Ubuntu" -Wait -Verb RunAs
  tags: wsl
