---
- name: Garantir que o Chocolatey esteja instalado
  win_chocolatey:
    name: chocolatey
    state: present
  tags: mysql

- name: Matar processos relacionados ao mysqld
  win_shell: |
    Stop-Process -ProcessName mysqld -Force
  ignore_errors: yes
  tags: mysql
  no_log: true

- name: Matar processos relacionados ao admin
  win_shell: |
    Stop-Process -ProcessName mysqladmin -Force
  ignore_errors: yes
  tags: mysql
  no_log: true

- name: Desinstalar MySQL (community edition) via choco
  win_chocolatey:
    name: mysql
    state: absent
  tags: mysql

- name: Remover diretório do MySQL
  win_file:
    path: "C:\\tools\\mysql"
    state: absent
  tags: mysql

- name: Remover diretório de dados do MySQL
  win_file:
    path: "C:\\ProgramData\\MySQL"
    state: absent
  tags: mysql

- name: Instalar MySQL (community edition) via choco
  win_chocolatey:
    name: mysql
    state: present
  tags: mysql

- name: Definir senha do usuário root do MySQL
  win_shell: |
    & "C:\tools\mysql\current\bin\mysqladmin.exe" -u root password "{{ mysql_root_password }}"
  tags: mysql

- name: Criar Banco de dados para o Laboratório
  win_shell: |
    & mysql.exe `
      -u root `
      -p"{{ mysql_root_password }}" `
      -e "CREATE DATABASE laboratorio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  no_log: true
  tags: mysql


- name: Criar Usuário para o Laboratório
  win_shell: |
    & mysql.exe `
      -u root `
      -p"{{ mysql_root_password }}" `
      -e "CREATE USER 'laboratorio'@'localhost' IDENTIFIED BY 'laboratorio';"
  no_log: true
  tags: mysql

- name: Resolvendo permissões
  win_shell: |
    & mysql.exe `
      -u root `
      -p"{{ mysql_root_password }}" `
      -e "GRANT ALL PRIVILEGES ON laboratorio.* TO 'laboratorio'@'localhost'; FLUSH PRIVILEGES;"
  tags: mysql

- name: Criar Diretório de Configurações do dbeaver
  win_file:
    path: "{{ dbeaver_dst_dir }}"
    state: directory
  tags: mysql

- name: Copiar arquivo data-sources.json
  ansible.windows.win_copy:
    src: "{{ dbeaver_src }}"
    dest: "{{ dbeaver_dst_file }}"
  tags: mysql

- name: Copiar arquivo de credenciais (usuário local)
  ansible.windows.win_copy:
    src: "{{ dbeaver_credential }}"
    dest: "{{ dbeaver_dst_credential }}"
  tags: mysql
