---
- name: Ativar recurso WSL (cliente Windows)
  win_optional_feature:
    name: Microsoft-Windows-Subsystem-Linux
    state: present
    include_parent: yes
  register: feat_wsl

- name: Ativar recurso VirtualMachinePlatform (cliente Windows)
  win_optional_feature:
    name: VirtualMachinePlatform
    state: present
    include_parent: yes
  register: feat_vmp


- name: Reboot se algum recurso foi alterado
  win_reboot:
  when: (feat_wsl.changed | default(false)) or (feat_vmp.changed | default(false))
